server:
  port: 9090
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anoop-pillai/configurations.git
          password: ${PAT}
          username: anoop-pillai
greeting:
  value: hello there