server:
  port: 9090
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anoop-pillai/configurations.git
          password: ${PAT}
          username: anoop-pillai
          clone-on-start: true
          default-label: master
  security:
    user:
      name: ${UNAME}
      password: ${PASSWORD}
