name: Trigger auto deployment for config-container-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/config-container-service-AutoDeployTrigger-657abe6c-6b64-47fb-877b-625f87f40995.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONFIGCONTAINERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONFIGCONTAINERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONFIGCONTAINERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONFIGCONTAINERSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONFIGCONTAINERSERVICE_REGISTRY_PASSWORD }}
          containerAppName: config-container-service
          resourceGroup: sample-rg
          imageToBuild: anoopktla@gmail.com/config-container-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


